#!/usr/bin/env python3
"""Bake the measured narration timings into the page.

The browser cannot fetch a local JSON file from a file:// page, so the timings
are written out as a plain script the page loads before the timeline. Run this
after voice.py, and any time the script changes.

    ./build.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
t = json.load(open(os.path.join(HERE, "vo", "timing.json")))
with open(os.path.join(HERE, "timings.js"), "w") as f:
    f.write("// Generated by build.py from vo/timing.json. Do not edit.\n")
    f.write("const T = " + json.dumps(t, indent=2) + ";\n")
print(f"timings.js written · {t['total']:.2f}s of narration, {len(t['lines'])} lines")
