#!/usr/bin/env python3
"""Bake the measured narration into the two files the render reads.

  vo/timing.json  ->  timings.js            the anchors the timeline is built on
  sound.json      ->  explainer.audio.json  the cue sheet, with every "at"
                                            resolved from a voice anchor to seconds

The browser cannot fetch a local JSON file from a file:// page, so the timings
are written out as a plain script the page loads before the timeline.

sound.json positions every cue the same way the timeline positions every
tween: relative to a line of the script.  "at": "print - 0.45"  means 0.45s
before she starts the line with id "print"; "end + 0.2" is after the last
word. Change a line, re-run voice.py and this, and the sound re-anchors with
the picture. render-audio.js only understands absolute seconds, hence the
resolved copy.

    ./build.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
t = json.load(open(os.path.join(HERE, "vo", "timing.json")))

with open(os.path.join(HERE, "timings.js"), "w") as f:
    f.write("// Generated by build.py from vo/timing.json. Do not edit.\n")
    f.write("const T = " + json.dumps(t, indent=2) + ";\n")
print(f"timings.js written · {t['total']:.2f}s of narration, {len(t['lines'])} lines")


def resolve(at):
    if isinstance(at, (int, float)):
        return float(at)
    m = re.fullmatch(r"\s*([a-z0-9]+)\s*(?:([+-])\s*([\d.]+))?\s*", at)
    if not m:
        raise SystemExit(f"bad anchor: {at!r}")
    name, sign, off = m.groups()
    base = t["total"] if name == "end" else t["lines"][name]["start"]
    return round(base + (float(off or 0) * (-1 if sign == "-" else 1)), 3)


snd = json.load(open(os.path.join(HERE, "sound.json")))
out = {"_comment": "GENERATED by build.py from sound.json — edit that, not this. "
                   "Every cue was anchored to a narration line and resolved to seconds here.",
       "seed": snd.get("seed", 1), "cues": []}
for c in snd["cues"]:
    cue = {k: v for k, v in c.items() if k not in ("at", "_")}
    cue = {"type": cue.pop("type"), "time": resolve(c["at"]), **cue}
    out["cues"].append(cue)
out["cues"].sort(key=lambda c: c["time"])
json.dump(out, open(os.path.join(HERE, "explainer.audio.json"), "w"), indent=1)
print(f"explainer.audio.json written · {len(out['cues'])} cues")
