// Generated by build.py from vo/timing.json. Do not edit.
const T = {
  "voice": "en-US-AvaNeural",
  "total": 75.246,
  "lines": {
    "hook": {
      "start": 0.6,
      "dur": 4.656,
      "end": 5.256,
      "text": "This is a content studio. It lives in your terminal, and you use it by talking to it."
    },
    "brand1": {
      "start": 5.556,
      "dur": 5.832,
      "end": 11.388,
      "text": "First run, an agent asks about your brand. Your colours, your type, the way you sound."
    },
    "brand2": {
      "start": 11.588,
      "dur": 4.872,
      "end": 16.46,
      "text": "It writes the answers into one file, and everything you make after that comes out on brand."
    },
    "ask": {
      "start": 16.81,
      "dur": 1.776,
      "end": 18.586,
      "text": "Then you just say what you want."
    },
    "carousel": {
      "start": 18.736,
      "dur": 7.296,
      "end": 26.032,
      "text": "A carousel about the new pricing. It writes the copy, builds the slides, renders the images, and shows you the picture."
    },
    "iterate": {
      "start": 26.232,
      "dur": 4.296,
      "end": 30.528,
      "text": "Slide two feels flat? Say so. It re-renders in seconds."
    },
    "deck": {
      "start": 30.878,
      "dur": 4.944,
      "end": 35.822,
      "text": "Decks work the same way. Seven slides, one PDF, ready to send."
    },
    "video1": {
      "start": 36.122,
      "dur": 2.688,
      "end": 38.81,
      "text": "Videos too, and this is the fun part."
    },
    "video2": {
      "start": 38.96,
      "dur": 9.216,
      "end": 48.176,
      "text": "Every frame is just HTML, screenshotted by a browser. The sound is synthesized from a little JSON file. There is no video editor anywhere in this."
    },
    "essay": {
      "start": 48.526,
      "dur": 6.96,
      "end": 55.486,
      "text": "Writing a long piece? You get the article, the hero image, the share card and the caption, all in one go."
    },
    "calendar": {
      "start": 55.786,
      "dur": 4.752,
      "end": 60.538,
      "text": "Tell it a post went out, and the calendar ticks itself and re-renders the board."
    },
    "agnostic": {
      "start": 60.888,
      "dur": 7.584,
      "end": 68.472,
      "text": "And it is not tied to one AI. It is just files and a folder of instructions, so point whichever model you already pay for at it."
    },
    "hour": {
      "start": 68.822,
      "dur": 2.976,
      "end": 71.798,
      "text": "One hour on a Monday gets you a week of content."
    },
    "close": {
      "start": 72.098,
      "dur": 3.048,
      "end": 75.146,
      "text": "It is open source. Yours in five minutes."
    }
  }
};
